FROM registry.docker-cn.com/library/openjdk:8u162
RUN apt-get update && apt-get install -y -q --no-install-recommends \
        maven \
    && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /tmp/backend \
	&& mkdir -p /tmp/frontend \
	&& mkdir /root/.m2
COPY pom.xml /tmp/
COPY backend/pom.xml /tmp/backend/
COPY frontend/pom.xml /tmp/frontend/
RUN echo '<?xml version="1.0" encoding="UTF-8"?><settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd"><mirrors><mirror><id>alirepo</id><mirrorOf>*</mirrorOf><name>maven.aliyun.com</name><url>http://maven.aliyun.com/nexus/content/groups/public/</url></mirror></mirrors></settings>' > /root/.m2/settings.xml \
	&& mvn -f /tmp/pom.xml clean dependency:resolve \
	&& rm -rf /tmp
ENV NVM_DIR /root/.nvm
ENV NODE_VERSION 8.1.3
RUN mkdir $NVM_DIR
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default
ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/v$NODE_VERSION/bin:$PATH
